### ISSUE TITLE
Level-8 Date task

### ISSUE THREAD

**Issue by adinata15** [nus-cs2113-AY2021S1/forum#69]
After implementing the `Date` on `Level-8`, can we assume the user can only register in the correct date format(YYYYMMDD) and nothing else(eg: 9 pm later)?

**Comment by zhixiangteoh** [comment]
It's not specified so I personally assumed it's up to the individual's discretion: my tp mate implemented error-checking to only allow the strict date formatting but I personally coded it such that if you get the right format (i.e. YYYYMMDD) the program converts it, otherwise it just uses whatever the user entered (e.g. in 10min). Either way, include it in your user guide!

**Comment by felixhalim** [comment]
I agree with @zhixiangteoh. There is no strict rule regarding that, hence, you might implement any variant but remember to provide relevant information on the user guide.

**Comment by okkhoy** [comment]
@felixhalim  and @zhixiangteoh  are correct.
We don't mandate what/how you want to handle these kinds of inputs. You can choose to do the minimum level if you only want to "pass the bar" (you will still get the credits). But you can also try to go further to do some validation and provide flexibility if you want to explore and learn. 
And yes, **_document it_** in your user guide!!

**Comment by adinata15** [comment]
Thank you for the clarification! @okkhoy @felixhalim @zhixiangteoh
